import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '🟪 THEME TEST 🟪',
  description: 'Generated by create next app',
};

function IndexPage() {
  return (
    <div>
      <p>Hello world!</p>
    </div>
  );
}

export default IndexPage;
