//^ LAYOUT.TSX
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '⬛NEXT____TRAINING⬛',
  description: 'Generated by create next app',
};

// COMPONENT
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2 className="bg-red-700 p-6 text-3xl font-black">HEADER</h2>
        {children}
        <h2 className="bg-blue-800 p-6 text-3xl font-black">FOOTER</h2>
      </body>
    </html>
  );
}
