//^ LAYOUT.TSX
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



// COMPONENT
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2 className="bg-gradient-to-r from-yellow-400 via-purple-500 to-red-800 p-7 text-center font-extrabold text-6xl text-black border-b-8 border-black">HEADER SECTION</h2>
        {children}
      </body>
    </html>
  );
}
