// AXIOS PAGE
import AXIOS from "@/Axios/AxiosInstance";
import AxiosProducts from "@/components/AxiosProducts";

export const metadata = {
  title: "🟪 AXIOS PAGE 🟪",
  description: "Generated by create next app",
};

const AxiosPage = async () => {
  const data = await AXIOS.get("/products", {
    signal: AbortSignal.timeout(3000),
  });

  console.log("ENV", process.env.NEXT_PUBLIC_NAME);

  return (
    <div>
      AxiosPage
      <AxiosProducts data={data.data} />
    </div>
  );
};
export default AxiosPage;
