//^ DYNAMIC COURSE PAGE
import React from 'react';
type SingleCoursePageParams = { params: { courseID: string } };

const SingleCoursePage = (params: any) => {
  console.info(params);
  return (
    <div>
      <h2 className="p-10 text-2xl font-bold w-fit mx-auto my-10 bg-white text-black rounded-2xl">{params.courseID.toUpperCase()} COURSE</h2>
    </div>
  );
};

export default SingleCoursePage;

// export function generateMetadata(params: any) {
//   return {
//     title: `🟪 ${params.courseID} TUTORIAL 🟪`,
//     description: 'Generated by create next app',
//   };
// }

// const generateStaticParams = async () => {
//   return [{ courseID: 'next' }, { courseID: 'node' }, { courseID: 'react' }];
// };
// export { generateStaticParams };
