import React from 'react';
import { redirect } from 'next/navigation';

type dynamicProductPageParams = { params: { id: string } };

// COMPONENT
const DynamicProductPage = async (params: dynamicProductPageParams) => {
  const pageParams = params.params.id;

  const request = await fetch(`https://fakestoreapi.com/products/${pageParams}`);

  if (Number(pageParams) > 20) {
    redirect('/product-not-found');
  }

  const response = await request?.json();

  //Return
  return (
    <section className="w-1/2 mx-auto rounded-3xl p-8 bg-zinc-900 shadow-2xl my-10">
      <div className="p-6 text-3xl text-center border-b-8 rounded-t-xl border-white bg-white text-black font-black">
        <h1>DYNAMIC PRODUCT PAGE</h1>
      </div>

      <div className="p-6 text-3xl font-black text-center border-b-8 border-red-800 bg-red-800 text-white">
        <h1>Page Params : {pageParams}</h1>
      </div>

      {response && (
        <div className="p-6 text-3xl font-black text-center border-b-8 border-blue-800 bg-blue-800 text-white rounded-b-xl">
          <h1>
            {response.id} - {response.title.slice(0, 30)} : ${response.price}
          </h1>
        </div>
      )}
    </section>
  );
};

export default DynamicProductPage;

// METADATA
export function generateMetadata({ params }: dynamicProductPageParams) {
  return {
    title: `🟪 PRODUCT ${params.id} 🟪`,
    description: 'Generated by create next app',
  };
}
export async function generateStaticParams() {
  return [{ id: '1' }, { id: '2' }, { id: '3' }, { id: '4' }, { id: '5' }, { id: '6' }, { id: '7' }, { id: '8' }, { id: '9' }, { id: '10' }, { id: '11' }, { id: '12' }, { id: '13' }, { id: '14' }, { id: '15' }, { id: '16' }, { id: '17' }, { id: '18' }, { id: '19' }, { id: '20' }];
}
